name: workflow-dispatch

on:
  workflow_dispatch:
    inputs:
      isBuildPdf:
        description: 'wheter build pdf of not'
        type: boolean
        required: true
        default: false
jobs:
  hoge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: debug isBuildPdf
        run: |
          echo "${{ inputs.isBuildPdf }}"
          echo "${{ github.event.inputs.isBuildPdf }}"
      - name: if ture
        if: ${{ inputs.isBuildPdf }}
        run: echo 'true'

      - name: if else
        if: ${{ ! inputs.isBuildPdf }}
        run: echo 'false'

      - name: if ture 2
        if: inputs.isBuildPdf
        run: echo 'true'

   # ! inputs.isBuildPdfはexpressionではない
   # The workflow is not valid. .github/workflows/dispatch.yml: (Line: 36, Col: 13, Idx: 753) - (Line: 36, Col: 14, Idx: 754): While parsing a tag, did not find expected tag URI.
   #   - name: if else 3
   #     if: ! inputs.isBuildPdf
   #     run: echo 'false'


